# Generated by Django 5.2.1 on 2025-06-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
