# Generated by Django 5.2.1 on 2025-06-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Наличные', 'Наличные'), ('Электронно', 'Электронно')], default='Наличные', max_length=15, verbose_name='Способ оплаты'),
        ),
    ]
