# Generated by Django 5.2.1 on 2025-07-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('В сборке', 'В сборке'), ('Готовится', 'Готовится'), ('Доставляется', 'Доставляется'), ('Готов', 'Готов')], default='Новый', max_length=20, verbose_name='Статус'),
        ),
    ]
