# Generated by Django 5.2.1 on 2025-06-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_alter_order_called_at_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Наличные', 'Наличные'), ('Электронно', 'Электронно')], default='Наличные', max_length=15),
        ),
    ]
