# Generated by Django 5.2.1 on 2025-07-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, default=' ', verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
